### PR TITLE
added sslca options from mysql2 client

### PR DESCRIPTION
**Pull request by khetman**
options added from mysql2 lib to establish encryption

### CODE REVIEW

**Comment by toyama0919** [comment]
Thanks！

Please add this spec to README and test.

**Comment by jdhibberd** [comment]
@tagomoris, we'd love to use this feature in our deployment of fluent-plugin-mysql. Do you know roughly when you'll be able to merge this?

**Comment by nieldomingo** [comment]
@khetman @toyama0919 any chance for this to be merged? i'd like to help out in any way. i really need ssl support to be able to connect to aws aurora.

**Comment by toyama0919** [comment]
@khetman
Please rebase.

**Comment by toyama0919** [comment]
If this PR merged, v0.14 only support.
Please upgrade fluentd-0.14.

**Comment by khetman** [comment]
td-agent is not using v0.14 yet.

**Comment by toyama0919** [comment]
Duplicated PR https://github.com/tagomoris/fluent-plugin-mysql/pull/48
Close.

**Pull request closed without merging**
