### PR TITLE
out_mysql_bulk: Add on_duplicate_update_custom_values property.

### PR DESCRIPTION
**Pull request by MacoTasu**
I'd like to handle sql value, if duplicate error record update.

```json
{"id":"1","date":"2016-11-01","view_count":"1"}
```

```sql
CREATE TABLE `item` (
  `id` int(10) NOT NULL,
  `date` date NOT NULL,
  `view_count` int(6) NOT NULL DEFAULT '0',
  PRIMARY KEY (id`,`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
```

When I insert a json of example in the table, In the first insert, use the value of the insert. 
The second time or later, I want to increment the view_count by ``view_count = `view_count` + 1``.  The processing of update is considered that there is a variety of cases, I sent a PR want to support them.

How about adding on_duplicate_update_custom_values property?
Please give advise.

### CODE REVIEW

**Comment by toyama0919** [comment]
Good feature.

But I feel on_duplicate_update_custom_values redundancy.

Why use on_duplicate_update_keys?
I think on_duplicate_update_keys define placeholder.

**Comment by toyama0919** [comment]
>Why use on_duplicate_update_keys?

Hmm.. Sorry, this is difficult.

**Comment by toyama0919** [comment]
LGTM.

**Comment by toyama0919** [comment]
@MacoTasu 

released.

[fluent-plugin-mysql | RubyGems.org | your community gem host](https://rubygems.org/gems/fluent-plugin-mysql)

**Comment by MacoTasu** [comment]
Thank you for quick response and release !

**Pull request merged**
