### PR TITLE
Feature/fluentd v0.12.x only support latest version

### PR DESCRIPTION
**Pull request by toyama0919**
related https://github.com/tagomoris/fluent-plugin-mysql/pull/35

v0.1.5 is fluentd v0.12.x only support latest version.

### CODE REVIEW

**Comment by tagomoris** [comment]
LGTM.

**Comment by toyama0919** [comment]
@cosmo0920

**Comment by cosmo0920** [comment]
LGTM!

**Comment by toyama0919** [comment]
released.

[fluent-plugin-mysql | RubyGems.org | your community gem host](https://rubygems.org/gems/fluent-plugin-mysql/versions/0.1.5)

**Pull request merged**
