### PR TITLE
Enable SSL options for mysql database connection

### PR DESCRIPTION
**Pull request by jp-gc**
Enable the SSL options for the mysql connection. The parameters are passed on to to Mysq2 client. The parameters are similar to mysql2 client ( https://github.com/brianmario/mysql2 )

### CODE REVIEW

**Comment by toyama0919** [comment]
LGTM.

memo.
https://github.com/brianmario/mysql2#ssl-options

@tagomoris 
Is there anything to worry about?

**Comment by tagomoris** [comment]
This change doesn't include `sslverify` option. Is it intentional?
IMO it's needed.

**Comment by jp-gc** [comment]
I have modified the patch to include "sslverify" option.

**Comment by tagomoris** [comment]
LGTM.

**Comment by toyama0919** [comment]
Thanks. merged

**Comment by toyama0919** [comment]
v0.3.0 released!

[fluent\-plugin\-mysql \| RubyGems\.org \| your community gem host](https://rubygems.org/gems/fluent-plugin-mysql/versions/0.3.0)

**Pull request merged**
