### PR TITLE
Support multi workers

### PR DESCRIPTION
**Pull request by okkez**

### CODE REVIEW

**Comment by okkez** [comment]
@tagomoris Is there any chance to merge this PR?

**Comment by tagomoris** [comment]
Oops, I'm so sorry that I missed this pull-request.
If this plugin is available concurrently from 2 or more Fluentd nodes (and doesn't make any local file data), it's ready for multi workers.
So, I think this pull-request is ok for merge.

@toyama0919 Any ideas?

**Comment by toyama0919** [comment]
@okkez @tagomoris 

Sorry bad response!!
LGTM.

**Comment by toyama0919** [comment]
v0.3.0 released!

[fluent\-plugin\-mysql \| RubyGems\.org \| your community gem host](https://rubygems.org/gems/fluent-plugin-mysql/versions/0.3.0)

**Pull request merged**
