### PR TITLE
Add config descriptions

### PR DESCRIPTION
**Pull request by cosmo0920**

### CODE REVIEW

**Comment by cosmo0920** [comment]
I didn't add config descriptions against `out_mysql`. Because it is marked as deprecated.

**Comment by toyama0919** [comment]
Thanks :blush:

**Comment by toyama0919** [comment]
released.

[fluent-plugin-mysql | RubyGems.org | your community gem host](https://rubygems.org/gems/fluent-plugin-mysql/)

**Comment by cosmo0920** [comment]
:+1:

**Pull request merged**
