### PR TITLE
Added sslca options

### PR DESCRIPTION
**Pull request by khetman**
Options added for mysql2 sslca to establish ssl encryption.

### CODE REVIEW

**Comment by toyama0919** [comment]
Please to be minimum diff.

**Comment by toyama0919** [comment]
Please close duplicate pull request.

**Comment by khetman** [comment]
Additional pull requests removed.  Please advise if this request appears to be in the desired state now.  Thanks.

**Comment by toyama0919** [comment]
Please out_mysql_bulk.rb to be minimum diff.
I can't review for all diff.

**Pull request closed without merging**
