### PR TITLE
Added json_key_names property in order to store values as json string.

### PR DESCRIPTION
**Pull request by metheglin**
I'd like to handle the logs which include nested json such like below.

```
{
  "url": "/",
  "params": {
    "limit": 5,
    "offset": 15
  },
  "request_headers": {
    "Authorization": "Bearer ***"
  },
  "created_at": "2016-02-18 00:00:00"
}
```

```
create table `access` (
  `id` int(10) not null auto_increment,
  `url` varchar(256) not null,
  `remote_ip` varchar(32) not null,
  `params_json` text,
  `request_headers_json` text,
  `created_at` datetime not null,
  primary key (`id`)
)
```

I confirmed the original version can store nested json but they're stored as the ruby hash encoded string because maybe stored as to_s of record[key]. I'd like to fetch and parse them from any environments.
How about adding json_key_names property?
Please give advise.

### CODE REVIEW

**Comment by toyama0919** [comment]
Hmm..

I think json_key_names param is not need.
I think if value type is hash, convert to_json.

What do you think?

Other solution,,, This plugin use mysql2-cs-bind.
mysql2-cs-bind send pull request, hash condition add is better.

https://github.com/tagomoris/mysql2-cs-bind/blob/master/lib/mysql2-cs-bind.rb#L32

cc: @tagomoris

**Comment by metheglin** [comment]
> I think if value type is hash, convert to_json.

> mysql2-cs-bind send pull request, hash condition add is better.

Thank you for the alternatives. Either would be fine for me.
But I worried about backward compatibility a little.
I don't have strong confidence whether we should be sensitive to keep such a compatibility in this plugin.
How about this point?

In my opinion, I prefer your first suggestion.
In the case of mysql-cs-bind pull request,
Array is converted to comma separated string but Hash will be converted to json.
This is little confusing I think.

**Comment by tagomoris** [comment]
@metheglin 's points are reasonable for me. IMO it's better to specify fields list to stringify as json rather than serialize Array/Hash as JSON in default.

**Comment by toyama0919** [comment]
> IMO it's better to specify fields list to stringify as json rather than serialize Array/Hash as JSON in default.

>In my opinion, I prefer your first suggestion.
>In the case of mysql-cs-bind pull request,
>Array is converted to comma separated string but Hash will be converted to json.
>This is little confusing I think.

I see.
Merged.

**Comment by toyama0919** [comment]
released.

[fluent-plugin-mysql | RubyGems.org | your community gem host](https://rubygems.org/gems/fluent-plugin-mysql)

**Pull request merged**
